# Generated by Django 3.2.3 on 2021-05-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time_added', models.DateField(auto_created=True)),
                ('task_text', models.CharField(max_length=200)),
            ],
        ),
    ]
