# Generated by Django 3.2.3 on 2021-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_time_added',
            field=models.DateField(verbose_name='date time'),
        ),
    ]
